### ISSUE TITLE
cross -> curve BROKEN bug

### ISSUE THREAD

**Issue by ash-rus** [JustinStitt/pipe-dream#8]
the water is not moving and now i am sad

<img width="536" alt="Capture" src="https://user-images.githubusercontent.com/112121491/223578742-7465a249-8860-4458-9a8b-c96174bd99c1.PNG">

**Comment by ash-rus** [comment]
it will NOT work if you put a cross going into a curve!
<img width="535" alt="Capture" src="https://user-images.githubusercontent.com/112121491/223579617-02ecce20-c3e8-4bea-b397-63a0ecdbc2ea.PNG">

**Comment by ash-rus** [comment]
idk it works sometimes but not others 🤷 

<img width="533" alt="Capture" src="https://user-images.githubusercontent.com/112121491/223580141-98fa00aa-a5ac-4709-ab6f-eaca777bc931.PNG">

**Comment by JustinStitt** [comment]
Can't replicate.

**Comment by JustinStitt** [comment]
Fixed > e6fd7bb3314c6d7bf0e98b5a6f680bd51b8c65e9 <. Thanks for the report @ash-rus
